spring:
  datasource:    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ferho    driver-class-name: org.postgresql.Driver
  jpa:    hibernate:      ddl-auto: create-drop
    show-sql: true